### ISSUE TITLE
Sample any.msf file can't be parsed because of the slash comments

### ISSUE THREAD

**Issue by sjossi** [LtPeriwinkle/mist#10]
I pulled and compiled today and the any.msf file from the release.zip does not parse with "File parse failed. Do you want to try another?"

Inserting some debug information reveals that I get an "1:1658: Unexpected end of file" in mist-core in msf.rs on line 81 for the from_str(&data).

Playing around a bit it seems to be the `//` comments, since a file with `/* */` comments parses well.

I'm afraid I'm not rustacean enough to propose a good fix or find the root cause (didn't find the string in `ron`), but I might dig in some more when I have time later.

Fixed: [any.txt](https://github.com/LtPeriwinkle/mist/files/7849464/any.txt)
From release.zip: [broken.txt](https://github.com/LtPeriwinkle/mist/files/7849465/broken.txt)

System is a MacOS 11.6, but was also observed on Debian Linux. Let me know if you need more information.

**Comment by LtPeriwinkle** [comment]
Weird, ron claims to support single-line comments, and I thought it had worked before, but it clearly doesn't. I'll look into it.
