### ISSUE TITLE
`Instant` is not suitable for measuring time

### ISSUE THREAD

**Issue by CryZe** [LtPeriwinkle/mist#7]
A couple of hours ago the libs team decided that the time that the PC is suspended should not be counted, meaning that Instant as they decided is not entirely suitable anymore for measuring speedrun times (maybe your PC goes to sleep during some long segment while doing a speedrun on a console for example). I'm looking into forking it atm.

https://github.com/rust-lang/rust/pull/87907#issuecomment-901394948

**Comment by LtPeriwinkle** [comment]
Thanks for bringing this to my attention. I'll probably implement an `Instant` for mist then, or eventually borrow yours from livesplit-core I suppose.
